name: Migrate

on: workflow_dispatch

jobs:
  Clear:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy ssh key
        run: touch private_key && echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
      - name: Add key to keyring
        run: ssh -i private_key -o StrictHostKeyChecking=accept-new root@${{ secrets.SSH_HOST }}
      - name: Down server
        run: ssh -i private_key root@${{ secrets.SSH_HOST }} 'cd ~/bakend-api; touch .env; make down'
  Prepare:
    runs-on: ubuntu-latest
    needs: [Clear]
    steps:
      - uses: actions/checkout@v2
      - name: Copy ssh key
        run: touch private_key && echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
      - name: Add key to keyring
        run: ssh -i private_key -o StrictHostKeyChecking=accept-new root@${{ secrets.SSH_HOST }}
      - name: Set up environment
        run: ssh -i private_key root@${{ secrets.SSH_HOST }} 'cd ~/bakend-api; echo -e "${{ secrets.ENV_CONTENTS_DEV }}" > .env'
      - name: Build development stand
        run: ssh -i private_key root@${{ secrets.SSH_HOST }} 'cd ~/bakend-api; git pull; docker-compose build --no-cache'
  Services:
    runs-on: ubuntu-latest
    needs: [Prepare]
    steps:
      - uses: actions/checkout@v2
      - name: Copy ssh key
        run: touch private_key && echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
      - name: Add key to keyring
        run: ssh -i private_key -o StrictHostKeyChecking=accept-new root@${{ secrets.SSH_HOST }}
      - name: Make postgrsql
        run: ssh -i private_key root@${{ secrets.SSH_HOST }} 'cd ~/bakend-api; docker-compose up -d postgresql'
  Migrate:
    runs-on: ubuntu-latest
    needs: [Services]
    steps:
      - uses: actions/checkout@v2
      - name: Copy ssh key
        run: touch private_key && echo -e "${{ secrets.SSH_PRIVATE_KEY }}" > private_key && chmod 600 private_key
      - name: Add key to keyring
        run: ssh -i private_key -o StrictHostKeyChecking=accept-new root@${{ secrets.SSH_HOST }}
      - name: Make migrations
        run: ssh -i private_key root@${{ secrets.SSH_HOST }} 'cd ~/bakend-api; docker-compose up migrator'


